#!/usr/bin/env sh

# Exit if any subcommand fails
set -e

# Set up Ruby dependencies via Bundler.
gem install bundler --conservative
gem install jekyll html-proofer
bundle check || bundle install
bundle update
#webpack
bundle exec jekyll build
bundle exec htmlproofer ./_site